PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE staff(
ID INTEGER PRIMARY KEY,
FIRST_NAME TEXT NOT NULL,
LAST_NAME TEXT NOT NULL,
USERNAME TEXT NOT NULL,
PASSWORD TEXT NOT NULL,
DOCTOR BOOLEAN NOT NULL,
TEAM_ID INT NOT NULL
);
CREATE TABLE patients(
ID INTEGER PRIMARY KEY,
FIRST_NAME TEXT NOT NULL,
LAST_NAME TEXT NOT NULL,
BIRTH_DATE TEXT NOT NULL,
PHONE_NUM INT,
EMAIL TEXT,
ADDRESS_LINE1 TEXT,
ADDRESS_LINE2 TEXT,
ADDRESS_STATE TEXT,
ADDRESS_COUNTRY TEXT,
ADDRESS_ZIP INT,
INSURANCE TEXT,
INSURANCE_ID TEXT,
INSURANCE_GROUP TEXT,
PHARM_NAME TEXT,
PHARM_ADDRESS TEXT,
PHARM_STATE TEXT,
PHARM_COUNTRY TEXT,
PHARM_ZIP INT,
HEALTH_HISTORY TEXT,
MEDICATION_HISTORY TEXT,
IMMUNE_HISTORY TEXT,
DOCTOR_ID INT NOT NULL,
FOREIGN KEY (DOCTOR_ID) REFERENCES staff (ID)
);
CREATE TABLE messages(
ID INTEGER PRIMARY KEY,
MESSAGE_BODY TEXT NOT NULL,
DATE_LONG TEXT NOT NULL,
SENDER INT NOT NULL,
PATIENT_ID INT NOT NULL,
FOREIGN KEY(PATIENT_ID) REFERENCES patients(ID)
);
CREATE TABLE appointments(
ID INTEGER PRIMARY KEY,
DATE_LONG TEXT NOT NULL,
PAST_BOOL BOOLEAN NOT NULL,
BODY_TEMP REAL,
WEIGHT REAL,
HEIGHT REAL,
BLOOD_PRESSURE1 INT,
BLOOD_PRESSURE2 INT,
ALLERGIES TEXT,
DIAGNOSIS TEXT,
PRESCRIPTION TEXT,
SENT_TO_PHARM BOOLEAN,
PATIENT_ID INT NOT NULL,
FOREIGN KEY (PATIENT_ID) REFERENCES patients (ID)
);
INSERT INTO staff(ID, FIRST_NAME, LAST_NAME, USERNAME, PASSWORD, DOCTOR, TEAM_ID)
VALUES
(1, 'Amy', 'Cook', 'AmyCook', 'passwort369', 'YES', 0),
(2, 'Jim', 'Daly', 'JimDaly', 'passwort246', 'YES', 1),
(3, 'Sam', 'Smit', 'SamSmit', 'passwort789', 'NO', 0),
(4, 'Kat', 'Cena', 'KatCena', 'passwort123', 'NO', 1);
COMMIT;
